page_title: null
ios_app_id: 1672840991
ios_app_country: pt
appstore_link: null
playstore_link: null
presskit_download_link: 'https://ezefranca.com/amarelinhos/presskit'
app_icon: null
app_name: null
app_price: null
app_description: Write a short tagline for your app.
enable_smart_app_banner: true
your_name: ezefranca
your_link: 'https://ezefranca.com'
your_city: Lisbon
email_address: ezefranca.br@gmail.com
twitter_username: ezefranca
github_username: ezefranca
features:
  - title: Bus Route Search
    description: >-
      Explore all the bus lines across the Lisbon District with our
      comprehensive list of routes. Use the council filter to quickly find the
      lines that are most relevant to you.
    fontawesome_icon_name: fa-bus
  - title: Favorite Lines
    description: >-
      Save your favorite bus lines for quick and easy access in one convenient
      location. The favorite lines screen provides all the information you need,
      including availability, time schedule, maps, route, next service, and the
      option to enable live activity.
    fontawesome_icon_name: fa-heart
  - title: App Settings
    description: >-
      Customize the app to your liking with our easy-to-use settings view.
      Access privacy controls, a small Moovit widget, and a speedometer, all
      from one central location.
    fontawesome_icon_name: fa-cog
  - title: Line Details View
    description: >-
      Get all the information you need about a specific bus line in one
      easy-to-use screen. The Line Details View shows availability, time
      schedule, maps, route, next service, and the option to favorite, as well
      as the option to enable live activity.
    fontawesome_icon_name: fa-info-circle
  - title: Council Filter
    description: >-
      Easily find the bus lines that are most relevant to you with our
      convenient council filter. This feature lets you quickly filter the list
      of bus lines by council, so you can easily find the ones that serve your
      area.
    fontawesome_icon_name: fa-filter
  - title: Live Activity
    description: >-
      Get real-time information about your favorite bus lines with our live
      activity feature. Simply enable live activity for your favorite lines, and
      you'll receive notifications about delays, changes, and other important
      information.
    fontawesome_icon_name: fa-bell
  - title: Comprehensive Information
    description: >-
      Our app provides all the information you need about bus lines across the
      Lisbon District. From availability and schedules to maps and routes, we've
      got you covered.
    fontawesome_icon_name: fa-clipboard
  - title: Multi-language Support
    description: >-
      Our app supports multiple languages, so you can easily use it no matter
      what language you speak. Choose your preferred language from the settings
      view.
    fontawesome_icon_name: fa-language
topbar_color: '#000000'
topbar_transparency: 0.1
topbar_title_color: '#ffffff'
cover_image: assets/headerimagenew.png
cover_overlay_color: '#363b3d'
cover_overlay_transparency: 0.8
device_color: yellow
body_background_color: '#ffffff'
link_color: '#1d63ea'
app_title_color: '#ffffff'
app_price_color: '#ffffff'
app_description_color: '#ffffff'
feature_title_color: '#000000'
feature_text_color: '#666666'
feature_icons_foreground_color: '#1d63ea'
feature_icons_background_color: '#e6e6e6'
social_icons_foreground_color: '#666666'
social_icons_background_color: '#e6e6e6'
footer_text_color: '#666666'
sass:
  style: ':compressed'
exclude:
  - LICENSE
  - README.md
  - CNAME
collections:
  pages:
    output: true
    permalink: '/:path/'
markdown: kramdown
